### ISSUE TITLE
Overall Summary (16/16)

### ISSUE THREAD

**Issue by sjlagasse** [rossberto/be-project3-cc#5]
Great job on this project. You got everything to work just as intended. Your code looks great and you definitely understand the fundamentals of building an API. Great job on your folder structure as well. Lastly, looks like you were able to get the YAML working. Awesome job putting in the extra effort for the extra credit.

**Comment by rossberto** [comment]
Thank you for the feedback. Just one question, I did a new commit to solve the dependency vulnerabilities, do I need to resubmit the project in order to mark the project as completed?

**Comment by sjlagasse** [comment]
No, you don't need to worry about the vulnerabilities. That's something Codecademy needs to fix on their end. You're all set.

**Comment by rossberto** [comment]
Ok, thank you.
